version: '3.8'

services:
  yii2:
    container_name: yii2-docker-app
    image: voronbeats/myphp:latest
    restart: always
    ports:
      - "8080:80"
    volumes: 
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=yii2
      - DB_USER=root
      - DB_PASSWORD=rootpassword 

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yii2
    ports:
      - "3306:3306" # Пробрасываем порт 3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: # Персистентное хранилище для базы данных
