version: '3.8'

services:
  yii2:
    container_name: yii2-docker-app
    image: voronbeats/myphp:latest
    restart: always
    ports:
      - "4413:80"
    volumes: 
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
      - APACHE_DOCUMENT_ROOT=/var/www/html/frontend/web

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yii2
    ports:
      - "3306:3306" # Пробрасываем порт 3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: # Персистентное хранилище для базы данных
